-- Custom Résumé feature: per-career tailored résumés generated by WF_custom_resume.
--
-- A user selects up to 3 careers from their assessment results; for each, an
-- n8n workflow produces a structured résumé JSON (re-framed toward the target
-- role) plus optional cover letter, scored for ATS compatibility. The JSON is
-- the source of truth — every template renders from it client-side via
-- @react-pdf/renderer, so switching templates is instant and no PDFs need to
-- be stored server-side.
--
-- This migration adds:
--   1. profiles.resume_full_data — a richer parse of the uploaded résumé
--      (contact details, full work history bullets, education institutions,
--      LinkedIn, languages). The existing profiles.resume_parsed_data column
--      stays untouched — it's shaped for survey pre-fill, not résumé output.
--   2. custom_resumes — one row per (user, career, generation).

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS resume_full_data JSONB,
  ADD COLUMN IF NOT EXISTS resume_full_data_extracted_at TIMESTAMPTZ;

COMMENT ON COLUMN public.profiles.resume_full_data IS
'Deep résumé parse used by the Custom Résumé feature: full contact details, role bullets, education institutions, LinkedIn, languages. Distinct from resume_parsed_data which is shaped for survey pre-fill. Re-extracted when resume_full_data_extracted_at is older than resume_uploaded_at.';

CREATE TABLE IF NOT EXISTS public.custom_resumes (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  report_id UUID NOT NULL REFERENCES public.reports(id) ON DELETE CASCADE,
  -- The career this résumé is tailored for. Nullable FK so a deleted section
  -- doesn't cascade-kill the résumé the user already generated and downloaded.
  career_section_id UUID REFERENCES public.report_sections(id) ON DELETE SET NULL,
  career_title TEXT NOT NULL,
  -- The template the user last viewed/downloaded with. Switching templates is
  -- a client-side render, so this is purely a UX-persistence hint.
  template_id TEXT NOT NULL DEFAULT 'ats-classic',
  -- Source of truth for the résumé. Structured JSON: summary, experience[],
  -- skills_grouped, education[], highlights[]. See docs/custom-resume-spec.md.
  resume_json JSONB NOT NULL,
  -- Optional cover letter, generated alongside if requested.
  cover_letter_json JSONB,
  -- 0–100 score from the ATS optimization pass.
  ats_score NUMERIC,
  -- { hit: [...], missing: [...] } — keywords from enriched_jobs the LLM hit
  -- or didn't. Shown to the user for transparency.
  keyword_coverage JSONB,
  -- Generation status. Inserted as 'processing' by the edge function and
  -- updated to 'completed' (or 'failed') by WF_custom_resume.
  status TEXT NOT NULL DEFAULT 'processing'
    CHECK (status IN ('processing', 'completed', 'failed')),
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_custom_resumes_user
  ON public.custom_resumes (user_id);
CREATE INDEX IF NOT EXISTS idx_custom_resumes_report
  ON public.custom_resumes (report_id);
CREATE INDEX IF NOT EXISTS idx_custom_resumes_section
  ON public.custom_resumes (career_section_id);

ALTER TABLE public.custom_resumes ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'custom_resumes'
      AND policyname = 'Users manage their own custom resumes'
  ) THEN
    CREATE POLICY "Users manage their own custom resumes"
      ON public.custom_resumes FOR ALL
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'custom_resumes'
      AND policyname = 'Service role full access on custom resumes'
  ) THEN
    CREATE POLICY "Service role full access on custom resumes"
      ON public.custom_resumes FOR ALL
      USING (auth.role() = 'service_role');
  END IF;
END $$;

COMMENT ON TABLE public.custom_resumes IS
'Per-career tailored résumés generated by WF_custom_resume. resume_json is the source of truth — every template renders from it client-side, no PDFs stored server-side.';
